name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0 # fetch all commits/branches

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "Deploy version $VER"
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Set up Python 3.9.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      #- name: Configure Git Credentials
      #  run: |
      #    remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      #    git config user.name github-actions[bot]
      #    git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      # - run: mkdocs gh-deploy --force
      # - run: mike deploy --push --update-aliases 0.16 latest
      # - name: mike deploy
      #   run: mike deploy --push --update-aliases ${{ github.ref_name }} latest --alias-type=redirect

      - name: mike list
        run: mike list
#      mkdocs gh-deploy --force