name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git fetch origin gh-pages:gh-pages --depth=1
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git show gh-pages:versions.json > previous.versions.json
          PREV_VER="$(jq -r '.[0].version' "previous.versions.json")"
          echo $PREV_VER

      - name: Set variables
        run: |
          VER=$(cat ver)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "Deploy version $PREV_VER --> $VER"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: mike list
        run: |
          mike deploy --update-aliases ${{ env.VERSION }} latest
          mike set-default latest
          mike list

      # - name: deploy
      #   run: mike deploy --push --update-aliases ${{ env.VERSION }} latest
