name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.x

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git Credentials
        run: |
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: mike deploy --push --update-aliases 0.16 latest --ignore-remote-status

      - run: mike list
#      mkdocs gh-deploy --force